# Generated by Django 5.2.1 on 2025-05-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('duration', models.PositiveIntegerField(default=21, verbose_name='Длительность (дней)')),
                ('type', models.CharField(choices=[('summer', 'Летняя'), ('winter', 'Зимняя'), ('season', 'Сезонная')], default='summer', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='tours/', verbose_name='Изображение')),
                ('available_seats', models.PositiveIntegerField(default=30, verbose_name='Свободные места')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
        ),
    ]
