# Generated by Django 5.2.1 on 2025-05-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('summer', 'Летняя'), ('winter', 'Зимняя'), ('season', 'Сезонная')], default='summer', max_length=10, verbose_name='Тип'),
        ),
    ]
