# Generated by Django 5.2.1 on 2025-06-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_tour_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='includes',
            field=models.TextField(default='Ежедневные оздоровительные процедуры\n5-разовое питание\nРазвлекательные мероприятия\nЭкскурсии и мастер-классы', help_text='Каждый пункт с новой строки', verbose_name='Что включено'),
        ),
        migrations.AddField(
            model_name='tour',
            name='program',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки', verbose_name='Программа'),
        ),
    ]
