# Generated by Django 5.2.1 on 2025-06-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_tour_includes_tour_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='detailed_description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
    ]
