# Generated by Django 5.2.1 on 2025-06-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_tour_detailed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='includes',
            field=models.TextField(default='Заглушка', help_text='Каждый пункт с новой строки', verbose_name='Что включено'),
        ),
    ]
