# Generated by Django 5.2.1 on 2025-06-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('open', 'Открытая'), ('completed', 'Завершенная'), ('rejected', 'Отклонена')], default='open', max_length=20, verbose_name='Статус'),
        ),
    ]
