# Generated by Django 5.2.1 on 2025-05-31 10:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_completed',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь заполнил профиль', verbose_name='Профиль заполнен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+79999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя ребенка', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию ребенка', max_length=100, verbose_name='Фамилия')),
                ('birth_date', models.DateField(help_text='Укажите дату рождения в формате ДД.ММ.ГГГГ', verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мальчик'), ('F', 'Девочка')], max_length=1, verbose_name='Пол')),
                ('special_needs', models.TextField(blank=True, help_text='Аллергии, хронические заболевания и т.д.', verbose_name='Особенности здоровья')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Дети',
                'ordering': ['-created_at'],
            },
        ),
    ]
