# Generated by Django 5.2.1 on 2025-06-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_options_user_is_profile_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Родитель'), ('staff', 'Сотрудник'), ('admin', 'Администратор')], default='parent', max_length=10),
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
