# Generated by Django 5.2.1 on 2025-06-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_user_role_delete_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Родитель'), ('staff', 'Сотрудник')], default='parent', max_length=10),
        ),
    ]
