# Generated by Django 5.2.1 on 2025-06-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='child_age',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='child_name',
        ),
    ]
